### PR TITLE
Return Dataset[BinaryTile] so generated MVTs can be stored in a single output

### PR DESCRIPTION
**Pull request by mojodna**
# Overview

This is in addition to (optionally) writing individual MVTs out. This will save on object management and time taken to `PUT` individual tiles.

The single output contained generated MVTs can be subsequently processed to extract specific tiles or to write to an alternate data sink (e.g. MBTiles (#51)).

## Checklist

- [x] Add entry to CHANGELOG.md

### CODE REVIEW

**Comment by jpolchlo** [comment]
I approve of this concept.  Would be good for benchmarking purposes as well to cut out the costly write operation.  Would love to see if we can come up with a way to generate an MBTiles file out of one of these `Dataset[BinaryTile]` guys.

**Comment by jpolchlo** [comment]
Oh, but, we should hold off on deploying this until after 1.0.0

**Comment by jpolchlo** [comment]
This (I think) has been obviated by #140.  Reopen if that's not true.

**Comment by mojodna** [comment]
👋 Not quite (as far as I can imagine). I can imagine using `finalize` to output a single file(set) per zoom, but returning `Unit` from the end of the pipeline makes it difficult (impossible?) to accumulate (ideally lazily and optionally) all of the tiles for all of the zooms into a single data frame (and potentially re-group tiles from multiple zooms together).

**Pull request closed without merging**
