### PR TITLE
Taking Codacity for a Spin

### PR DESCRIPTION
**Pull request by fosskers**
A PR of corrections pointed out by Codacity.

### CODE REVIEW

**Comment by kamicut** [comment]
Codacity?

**Comment by fosskers** [comment]
Yeah I'm seeing if this has value for the team, using VectorPipe as a guinea pig.

https://www.codacy.com/app/fosskers/vectorpipe/dashboard

**Comment by kamicut** [comment]
That looks really nice! Thanks for sharing

**Comment by fosskers** [comment]
What you consider "bad" is also highly configurable.

**Pull request merged**
